Update Dockerfile
Added missing dependency to fix docker container:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wyoming_vosk/__main__.py", line 13, in <module>
    from vosk import KaldiRecognizer, Model, SetLogLevel
  File "/usr/local/lib/python3.11/dist-packages/vosk/__init__.py", line 36, in <module>
    _c = open_dll()
         ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vosk/__init__.py", line 30, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library '/usr/local/lib/python3.11/dist-packages/vosk/libvosk.so': libatomic.so.1: cannot open shared object file: No such file or directory